catalogs:
  min:
    astro: ^4.11.6
    vite: ^4 || ^5
  kit:
    astro-integration-kit: ^0.14.0
    kleur: ^4.1.5
    package-json: ^10.0.1
    semver: ^7.6.3
  dev:
    '@types/node': ^20.14.11
    '@types/semver': ^7.5.8
    typescript: ^5.5.3
    vite: ^5.3.4
  shared:
    astro: ^4.11.6

packages:
  - "package"
  - "playground"