catalogs:
  min:
    astro: ^4.12
    vite: ^4 || ^5
  kit:
    astro-integration-kit: ^0.16.0
    package-json: ^10.0.1
    semver: ^7.6.3
  dev:
    '@types/node': ^20.14.11
    '@types/semver': ^7.5.8
    typescript: ^5.5.3
    vite: ^5.3.4
  shared:
    astro: ^4.12.2

packages:
  - "package"
  - "playground"